# Nonlinear Optimizer Case Studies

Focused runs for selected chapter-2-style instances, comparing restarts and initialization effects while saving outputs under `results/optimizer_benchmarks/case_studies/`.

In [1]:
from pathlib import Path
import pandas as pd

from mpmgame.benchmark_suite import benchmark_problem_registry, run_benchmark_suite
from mpmgame.realization_report import write_realization_markdown_from_csv

RESULTS_DIR = Path('../results/optimizer_benchmarks/case_studies').resolve()
REPORTS_DIR = Path('../reports/optimizer_benchmarks/case_studies').resolve()
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
print('results:', RESULTS_DIR)
print('reports:', REPORTS_DIR)

results: C:\Users\perry\Documents\VSCode\masked-perturbation-model\results\optimizer_benchmarks\case_studies
reports: C:\Users\perry\Documents\VSCode\masked-perturbation-model\reports\optimizer_benchmarks\case_studies

## Case study A: Full attacker on 3x3 toy

In [2]:
case_a = [p for p in benchmark_problem_registry('full') if p.problem_id == 'toy3_w1_full']
algos_a = ['Nelder-Mead', 'Powell', 'SLSQP', 'trust-constr', 'differential_evolution', 'basinhopping']
raw_a, summary_a = run_benchmark_suite(
    problem_specs=case_a,
    algorithms=algos_a,
    n_restarts=10,
    timeout_per_run_sec=60,
    algorithm_timeout_sec=12 * 60,
    output_dir=RESULTS_DIR / 'case_a',
    report_dir=REPORTS_DIR / 'case_a',
    incremental_notes_dir=REPORTS_DIR / 'case_a' / 'incremental_notes',
    seed=101,
    show_progress=True,
    maxiter=300,
)
display(summary_a.sort_values('best_feasible_objective'))

Problems:   0%|          | 0/1 [00:00<?, ?it/s]

Algorithms:toy3_w1_full:   0%|          | 0/6 [00:00<?, ?it/s]

Restarts:Nelder-Mead:   0%|          | 0/10 [00:00<?, ?it/s]

Restarts:Powell:   0%|          | 0/10 [00:00<?, ?it/s]

Restarts:SLSQP:   0%|          | 0/10 [00:00<?, ?it/s]

Restarts:trust-constr:   0%|          | 0/10 [00:00<?, ?it/s]

Restarts:differential_evolution:   0%|          | 0/10 [00:00<?, ?it/s]

Restarts:basinhopping:   0%|          | 0/10 [00:00<?, ?it/s]

,problem_id,algorithm,runs,best_feasible_objective,median_feasible_objective,fraction_feasible,fraction_timeout,mean_runtime_sec,best_runtime_to_feasible,robustness_score
0,toy3_w1_full,Nelder-Mead,10,0.706888,0.706888,1.0,0.0,0.045975,0.011769,8.757585e-01
6,toy3_w1_full,basinhopping,10,0.706888,0.706888,1.0,0.0,1.108554,1.004672,8.757585e-01
7,toy3_w1_full,differential_evolution,10,0.706888,0.706888,1.0,0.0,0.252642,0.195111,8.757585e-01
1,toy3_w1_full,Powell,10,0.706888,0.706888,1.0,0.0,0.071888,0.031987,8.757585e-01
2,toy3_w1_full,SLSQP,10,0.706888,0.706888,1.0,0.0,0.005671,0.003425,8.757585e-01
8,toy3_w1_full,trust-constr,10,0.706888,0.706888,0.9,0.0,0.024069,0.014525,8.057585e-01
4,toy3_w1_full,baseline_projection,1,0.706888,0.706888,1.0,0.0,0.025427,0.025427,8.757585e-01
5,toy3_w1_full,baseline_zero,1,0.706888,0.706888,1.0,0.0,0.000000,0.000000,8.757585e-01
3,toy3_w1_full,baseline_lp,1,inf,inf,0.0,0.0,0.034766,inf,3.000000e-07

## Case study B: Single-link attacker on 3x3 toy

In [3]:
case_b = [p for p in benchmark_problem_registry('quick') if p.problem_id == 'toy3_w2_single']
algos_b = ['COBYLA', 'SLSQP', 'L-BFGS-B', 'dual_annealing', 'shgo']
raw_b, summary_b = run_benchmark_suite(
    problem_specs=case_b,
    algorithms=algos_b,
    n_restarts=8,
    timeout_per_run_sec=45,
    output_dir=RESULTS_DIR / 'case_b',
    report_dir=REPORTS_DIR / 'case_b',
    incremental_notes_dir=REPORTS_DIR / 'case_b' / 'incremental_notes',
    seed=202,
    show_progress=True,
    maxiter=250,
)
display(summary_b.sort_values('best_feasible_objective'))

Problems:   0%|          | 0/1 [00:00<?, ?it/s]

Algorithms:toy3_w2_single:   0%|          | 0/5 [00:00<?, ?it/s]

Restarts:COBYLA:   0%|          | 0/8 [00:00<?, ?it/s]

KeyboardInterrupt:

## Cross-case summary

In [ ]:
def best_by_algo(summary_df, label):
    out = summary_df[['algorithm', 'best_feasible_objective', 'fraction_feasible', 'mean_runtime_sec']].copy()
    out['case'] = label
    return out

combined = pd.concat([best_by_algo(summary_a, 'A'), best_by_algo(summary_b, 'B')], ignore_index=True)
display(combined.sort_values(['case', 'best_feasible_objective']))

,algorithm,best_feasible_objective,fraction_feasible,mean_runtime_sec,case
0,Nelder-Mead,0.706888,1.000,0.070832,A
1,basinhopping,0.706888,1.000,1.160595,A
2,differential_evolution,0.706888,1.000,0.132317,A
3,Powell,0.706888,1.000,0.111721,A
4,SLSQP,0.706888,1.000,0.007554,A
5,trust-constr,0.706888,1.000,0.027917,A
6,baseline_projection,0.706888,1.000,0.018634,A
7,baseline_zero,0.706888,1.000,0.000000,A
8,baseline_lp,inf,0.000,0.104013,A
9,dual_annealing,0.897716,0.875,9.310040,B
10,shgo,0.897716,1.000,10.808783,B
11,L-BFGS-B,0.897716,1.000,0.643440,B
12,SLSQP,0.897716,1.000,0.053704,B
13,COBYLA,0.920429,0.750,0.132698,B
14,baseline_zero,1.003034,1.000,0.000000,B
15,baseline_lp,inf,0.000,0.021645,B
16,baseline_projection,inf,0.000,0.077245,B

In [ ]:
for case in ['case_a', 'case_b']:
    raw_csv = RESULTS_DIR / case / 'benchmark_raw_results.csv'
    out_dir = REPORTS_DIR / case / 'realizations'
    out_dir.mkdir(parents=True, exist_ok=True)
    for pid in sorted(pd.read_csv(raw_csv)['problem_id'].unique()):
        write_realization_markdown_from_csv(raw_csv, out_dir / f'{pid}_best.md', problem_id=pid)

print('Saved case-study files:')
for f in sorted(RESULTS_DIR.rglob('*')):
    if f.is_file():
        print(' ', f.relative_to(RESULTS_DIR))
for f in sorted(REPORTS_DIR.rglob('*')):
    if f.is_file():
        print(' ', Path('reports') / f.relative_to(REPORTS_DIR.parent))

Saved case-study files:
  case_a\benchmark_raw_results.csv
  case_a\benchmark_summary.csv
  case_a\run_config.json
  case_b\benchmark_raw_results.csv
  case_b\benchmark_summary.csv
  case_b\run_config.json
  reports\case_studies\case_a\baseline_comparison.png
  reports\case_studies\case_a\benchmark_report.md
  reports\case_studies\case_a\best_feasible_bar.png
  reports\case_studies\case_a\best_q_heatmap.png
  reports\case_studies\case_a\convergence_traces.png
  reports\case_studies\case_a\feasibility_rate.png
  reports\case_studies\case_a\incremental_notes\toy3_w1_full\basinhopping.md
  reports\case_studies\case_a\incremental_notes\toy3_w1_full\differential_evolution.md
  reports\case_studies\case_a\incremental_notes\toy3_w1_full\Nelder-Mead.md
  reports\case_studies\case_a\incremental_notes\toy3_w1_full\Powell.md
  reports\case_studies\case_a\incremental_notes\toy3_w1_full\SLSQP.md
  reports\case_studies\case_a\incremental_notes\toy3_w1_full\trust-constr.md
  reports\case_studies\case_a\objective_boxplot.png
  reports\case_studies\case_a\realizations\toy3_w1_full_best.md
  reports\case_studies\case_a\runtime_vs_objective.png
  reports\case_studies\case_a\timeout_count.png
  reports\case_studies\case_b\baseline_comparison.png
  reports\case_studies\case_b\benchmark_report.md
  reports\case_studies\case_b\best_feasible_bar.png
  reports\case_studies\case_b\best_q_heatmap.png
  reports\case_studies\case_b\convergence_traces.png
  reports\case_studies\case_b\feasibility_rate.png
  reports\case_studies\case_b\incremental_notes\toy3_w2_single\COBYLA.md
  reports\case_studies\case_b\incremental_notes\toy3_w2_single\dual_annealing.md
  reports\case_studies\case_b\incremental_notes\toy3_w2_single\L-BFGS-B.md
  reports\case_studies\case_b\incremental_notes\toy3_w2_single\shgo.md
  reports\case_studies\case_b\incremental_notes\toy3_w2_single\SLSQP.md
  reports\case_studies\case_b\objective_boxplot.png
  reports\case_studies\case_b\realizations\toy3_w2_single_best.md
  reports\case_studies\case_b\runtime_vs_objective.png
  reports\case_studies\case_b\timeout_count.png